lightning:
  hosts:
    - { "name": "hostb1", 
        "interfaces": [ 
          { "name": "eth0", "ip": "192.168.1.17", "network": "blue" } ] }
    - { "name": "hostb2",
        "interfaces": [
          { "name": "eth0", "ip": "192.168.1.18", "network": "blue" } ] }
    - { "name": "hostr1",
        "interfaces": [
          { "name": "eth0", "ip": "10.10.1.100", "network": "red" } ] }
    - { "name": "hosty1",
        "interfaces": [ 
          { "name": "eth0", "ip": "10.10.1.101", "network": "red" }, 
          { "name": "eth1", "ip": "192.168.1.101", "network": "blue" } ] }

  networks:
    red: 
      netmask: "255.255.255.0"
      gateway: ""
      dns_servers:
        - "ntpr1"
        - "ntpr2"
    blue:
      netmask: "255.255.0.0"
      gateway: "10.10.1.1"
      dns_servers:
        - "ntpb1"
        - "ntpb2"
