---

- name: fist task
  include_vars:
    file: lightning_data.yaml
   
- name: lookup host data
  set_fact:
    host_data: "{{item}}"
  with_items: 
    - "{{ lightning.hosts }}"
  when: item.name == "hosty1"

- name: configure interface
  lineinfile:
    path: /tmp/resolv.conf
    regexp: "^nameserver "
    line: "nameserver {{lightning.networks[item.network]['dns_servers']|join(' ')}}"
    create: yes
    backup: yes
  with_items:
    - "{{host_data.interfaces}}"
